### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by zack-zzq**
Add Simplified Chinese translation

### CODE REVIEW

**Review by GizmoTheMoonPig — CHANGES_REQUESTED** [review]
Hi there! Thank you so much for the translation! I'd like to ask one thing before I merge this. It seems like a couple entries are missing from your file compared to the English one, would you mind adding these couple entries in for me? Here's the English lang file for reference: https://github.com/GizmoTheMoonPig/luggage/blob/1.19.x/src/main/resources/assets/luggage/lang/en_us.json

**Comment by zack-zzq** [comment]
@GizmoTheMoonPig 
Sure. The lost entries have been added.

**Comment by GizmoTheMoonPig** [comment]
Looks like you missed one. There's 2 subtitles, each one is tied to a different keybind. If you get those fixed I'll happily merge this. Thanks!

**Comment by zack-zzq** [comment]
Sorry for the mistake again : (
I've checked carefully this time, there'll be no problem.

**Comment by GizmoTheMoonPig** [comment]
It's fine man! I really appreciate it. Thank you so much for doing this!

**Pull request merged**
